// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:tempo_fit/flavor.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        if (isProduction()) {
          // 本番環境
          return android;
        } else {
          // 開発環境
          return android_dev;
        }
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqEMVDbPBaqiVZPc3pb5u1_PhhbenhcE',
    appId: '1:467022370886:android:7856ba6b5fe3c20258d247',
    messagingSenderId: '467022370886',
    projectId: 'tempo-fit-a5a19',
    storageBucket: 'tempo-fit-a5a19.appspot.com',
  );

  static const FirebaseOptions android_dev = FirebaseOptions(
    apiKey: 'AIzaSyA3jY54ioVtU31_JTXtFoFIs3H7H1zZ1aY',
    appId: '1:912911575736:android:ea2aae2d2cbd14a8ece24d',
    messagingSenderId: '912911575736',
    projectId: 'tempo-fit-dev',
    storageBucket: 'tempo-fit-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RdF5Z6DZNf_v-wTcx5nUQS6AkWedcdw',
    appId: '1:467022370886:ios:561cc92f45b75b3258d247',
    messagingSenderId: '467022370886',
    projectId: 'tempo-fit-a5a19',
    storageBucket: 'tempo-fit-a5a19.appspot.com',
    iosBundleId: 'com.jostory.intervalTimer',
  );
}
